const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

function loadEnvFile(filename) {
  const filePath = path.join(process.cwd(), filename);
  if (!fs.existsSync(filePath)) return;

  const content = fs.readFileSync(filePath, 'utf8');
  content.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) return;
    const key = match[1];
    let value = match[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!process.env[key]) {
      process.env[key] = value;
    }
  });
}

function loadLocalEnv() {
  loadEnvFile('.env.local');
  loadEnvFile('.env');
}

function getSupabaseDbUrl() {
  return (
    process.env.SUPABASE_DB_URL ||
    process.env.SUPABASE_DATABASE_URL ||
    process.env.POSTGRES_URL ||
    process.env.DATABASE_URL ||
    ''
  );
}

function createPool() {
  const connectionString = getSupabaseDbUrl();
  if (!connectionString) {
    throw new Error('Missing Supabase Postgres connection string. Add SUPABASE_DB_URL to .env.local.');
  }

  return new Pool({
    connectionString,
    ssl: process.env.SUPABASE_DB_SSL === 'false' ? false : { rejectUnauthorized: false },
  });
}

const schemaSql = `
CREATE TABLE IF NOT EXISTS user_credits (
  email TEXT PRIMARY KEY,
  password TEXT NOT NULL DEFAULT '12345688',
  credits INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS credit_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  type TEXT NOT NULL,
  amount INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  description TEXT NULL,
  stripe_payment_id TEXT NULL,
  stripe_session_id TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_credit_transactions_email ON credit_transactions(email);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_created_at ON credit_transactions(created_at DESC);

CREATE TABLE IF NOT EXISTS draw_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  sketch_url TEXT NOT NULL,
  generated_url TEXT NOT NULL,
  display_url TEXT NULL,
  style TEXT NOT NULL,
  prompt TEXT NULL,
  prompt_en TEXT NULL,
  prompt_zh TEXT NULL,
  description TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_draw_images_email ON draw_images(email);
CREATE INDEX IF NOT EXISTS idx_draw_images_created_at ON draw_images(created_at DESC);

CREATE TABLE IF NOT EXISTS temp_image_data (
  draw_image_id INTEGER PRIMARY KEY REFERENCES draw_images(id) ON DELETE CASCADE,
  input_base64 TEXT,
  output_base64 TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS diagnosis_sessions (
  id TEXT PRIMARY KEY,
  email TEXT NULL,
  status TEXT DEFAULT 'collecting_info',
  completeness INTEGER DEFAULT 0,
  profile_status TEXT DEFAULT 'idle',
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE diagnosis_sessions ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_diagnosis_sessions_email ON diagnosis_sessions(email);
CREATE INDEX IF NOT EXISTS idx_diagnosis_sessions_updated_at ON diagnosis_sessions(updated_at DESC);

CREATE TABLE IF NOT EXISTS diagnosis_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT REFERENCES diagnosis_sessions(id) ON DELETE CASCADE,
  sender TEXT,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_diagnosis_messages_session_id ON diagnosis_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_diagnosis_messages_created_at ON diagnosis_messages(created_at);

CREATE TABLE IF NOT EXISTS diagnosis_profiles (
  session_id TEXT PRIMARY KEY REFERENCES diagnosis_sessions(id) ON DELETE CASCADE,
  known_facts JSONB,
  missing_fields JSONB,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS diagnosis_reports (
  session_id TEXT PRIMARY KEY REFERENCES diagnosis_sessions(id) ON DELETE CASCADE,
  summary TEXT,
  maturity_score INTEGER DEFAULT 0,
  pain_points JSONB,
  opportunity_map JSONB,
  recommended_agents JSONB,
  roadmap_30_60_90 JSONB,
  risks JSONB,
  data_requirements JSONB,
  next_actions JSONB,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_user_credits_updated_at ON user_credits;
CREATE TRIGGER set_user_credits_updated_at
BEFORE UPDATE ON user_credits
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_diagnosis_sessions_updated_at ON diagnosis_sessions;
CREATE TRIGGER set_diagnosis_sessions_updated_at
BEFORE UPDATE ON diagnosis_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_diagnosis_profiles_updated_at ON diagnosis_profiles;
CREATE TRIGGER set_diagnosis_profiles_updated_at
BEFORE UPDATE ON diagnosis_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
`;

async function ensureSupabaseSchema(pool = createPool()) {
  await pool.query(schemaSql);
}

module.exports = {
  createPool,
  ensureSupabaseSchema,
  loadLocalEnv,
};

if (require.main === module) {
  loadLocalEnv();
  const pool = createPool();
  ensureSupabaseSchema(pool)
    .then(() => {
      console.log('Supabase schema is ready.');
    })
    .finally(() => pool.end());
}
